"""
Final validation: does the redacted DOCX actually contain zero known PII
from the original document?

This does NOT rely on the sampled paragraph-level evaluation (see
evaluation/). It re-runs full detection (structured regex + the same
document-wide entity registry used for redaction) against the ORIGINAL
document, then checks every one of those exact strings against the
REDACTED document's full text. Anything found in both is a leak.

This is the check that catches exactly the failure mode seen earlier in
this project: an evaluation report claiming good recall on a 120-paragraph
sample while the actual generated DOCX still contained real names/companies
that were simply never sampled.

Usage:
    python3 run.py validate
    python3 src/validate.py <original.docx> <redacted.docx>
"""
import sys
import os
import docx
import json

from redactor import PiiRedactor
from docx_processor import iter_paragraphs


def paragraph_texts(path):
    document = docx.Document(path)
    return [p.text for p in iter_paragraphs(document) if p.text and p.text.strip()]


def main(orig_path, redacted_path):
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    # Kept as separate per-paragraph strings, and scanned per-paragraph
    # below -- matching exactly how docx_processor.py builds the registry
    # and detects PII. Joining paragraphs with "\n" and scanning the whole
    # blob at once would let regexes match text spanning two unrelated
    # paragraphs (e.g. one paragraph ending "...Taluka-Khed" and the next
    # starting "Pune..."), which cannot happen in the real per-paragraph
    # pipeline and would produce phantom "leaks" that were never real.
    orig_paragraphs = paragraph_texts(orig_path)
    redacted_text = "\n".join(paragraph_texts(redacted_path))

    try:
        redactor = PiiRedactor()
    except OSError as exc:
        # Validation should still be able to run its independent manual
        # ground-truth audit in environments where the optional spaCy model
        # has not yet been downloaded. The full detector-derived audit is
        # skipped with an explicit warning rather than failing silently.
        print(f"WARNING: detector-derived audit skipped: {exc}")
        redactor = None

    # Rebuild the registry + collect every structured/address span from the
    # ORIGINAL document -- this is the full inventory of "known PII" we
    # expect to be gone from the output. Same two-pass shape as
    # docx_processor.main(): register every paragraph first, then detect.
    known = {}  # label -> set of original strings
    leaks = {}
    if redactor is not None:
        for t in orig_paragraphs:
            redactor.register_text(t)

        structured_spans = []
        for t in orig_paragraphs:
            structured_spans += redactor._find_structured(t) + redactor._find_address(t)

        for name in redactor.person_registry:
            known.setdefault("PERSON", set()).add(name)
        for name in redactor.company_registry:
            known.setdefault("COMPANY", set()).add(name)
        for s in structured_spans:
            known.setdefault(s.label, set()).add(s.text.strip())

        for label, values in known.items():
            for v in values:
                if not v:
                    continue
                if v in redacted_text:
                    leaks.setdefault(label, []).append(v)

    # Independent manual ground-truth audit.  This is deliberately loaded
    # from a hand-labeled fixture rather than generated by the detector being
    # tested.  It catches the exact failure mode where the detector misses an
    # entity completely (so a detector-derived registry could never validate
    # that entity).
    gt_path = os.path.join(root, "evaluation", "manual_ground_truth.json")
    independent = {}
    if os.path.exists(gt_path):
        with open(gt_path, encoding="utf-8") as f:
            gt = json.load(f)
        for label, values in gt.items():
            for value in values:
                independent.setdefault(label, set()).add(value.strip())

    independent_leaks = {}
    for label, values in independent.items():
        for v in values:
            if v and v in redacted_text:
                independent_leaks.setdefault(label, []).append(v)

    total_known = sum(len(v) for v in known.values())
    total_leaked = sum(len(v) for v in leaks.values())
    independent_total = sum(len(v) for v in independent.values())
    independent_leaked = sum(len(v) for v in independent_leaks.values())

    print("=" * 60)
    print("PII LEAK VALIDATION")
    print("=" * 60)
    for label, values in sorted(known.items()):
        leaked = leaks.get(label, [])
        status = "OK" if not leaked else "LEAK"
        print(f"  {label:12s} known={len(values):4d}  leaked={len(leaked):4d}  [{status}]")

    print("-" * 60)
    if redactor is None:
        print("Detector-derived audit: SKIPPED (spaCy model unavailable).")
    elif total_leaked == 0:
        print(f"Detector-derived audit: 0 of {total_known} detected PII entities remain.")
    else:
        print(f"Detector-derived audit FAILED: {total_leaked} of {total_known} detected PII entities remain:\n")
        for label, values in sorted(leaks.items()):
            print(f"  {label}:")
            for v in sorted(set(values)):
                print(f"    - {v!r}")

    if independent_leaked == 0:
        print(f"Independent ground-truth audit PASSED: 0 of {independent_total} manually "
              f"verified sample PII entities remain.")
    else:
        print(f"Independent ground-truth audit FAILED: {independent_leaked} of "
              f"{independent_total} manually verified sample PII entities remain:\n")
        for label, values in sorted(independent_leaks.items()):
            print(f"  {label}:")
            for v in sorted(set(values)):
                print(f"    - {v!r}")
    print("=" * 60)
    detector_ok = redactor is None or total_leaked == 0
    return 0 if detector_ok and independent_leaked == 0 else 1


if __name__ == "__main__":
    import sys
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8")
    if hasattr(sys.stderr, "reconfigure"):
        sys.stderr.reconfigure(encoding="utf-8")
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    orig = sys.argv[1] if len(sys.argv) > 1 else os.path.join(root, "input", "Red_Herring_Prospectus.docx")
    redacted = sys.argv[2] if len(sys.argv) > 2 else os.path.join(root, "output", "Red_Herring_Prospectus_REDACTED.docx")
    sys.exit(main(orig, redacted))
